services:
  cscflow-task:
    container_name: cscflow-task
    image: sacahan/cscflow-task:latest
    environment:
      - DATABASE_URL=postgresql+asyncpg://user:password@postgres:5432/cscflow
    networks:
      - sacahan-network
    restart: unless-stopped

  cscflow-flow:
    container_name: cscflow-flow
    image: sacahan/cscflow-flow:latest
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=%@z%dVBRS2f8io
      - DATABASE_URL=postgresql+asyncpg://user:password@postgres:5432/cscflow
    ports:
      - "8000:8000"
    networks:
      - sacahan-network
    restart: unless-stopped

networks:
  sacahan-network:
    external: true
