"""移除 location 欄位

Revision ID: 37bceec48d3d
Revises: 7596c81f6c63
Create Date: 2025-07-28 23:59:32.149455

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "37bceec48d3d"
down_revision: Union[str, Sequence[str], None] = "7596c81f6c63"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sport_centers", sa.Column("website_url", sa.String(length=255), nullable=False)
    )
    op.drop_column("sport_centers", "location")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sport_centers",
        sa.Column(
            "location",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("sport_centers", "website_url")
    # ### end Alembic commands ###
