"""移除 SportCenterResponse 的 formatted_address 欄位

Revision ID: 7596c81f6c63
Revises: fd2162902206
Create Date: 2025-07-28 23:30:35.481165

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7596c81f6c63"
down_revision: Union[str, Sequence[str], None] = "fd2162902206"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "historical_stats",
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=True),
    )
    op.drop_column("sport_centers", "formatted_address")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sport_centers",
        sa.Column(
            "formatted_address",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("historical_stats", "updated_at")
    # ### end Alembic commands ###
