"""Initial Setup

Revision ID: fd00725a3a98
Revises:
Create Date: 2025-07-29 23:41:13.204432

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fd00725a3a98"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "historical_stats",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("zip_code", sa.String(length=3), nullable=False),
        sa.Column("area_type", sa.String(length=5), nullable=False),
        sa.Column("avg_count", sa.Float(), nullable=False),
        sa.Column("max_count", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.CheckConstraint(
            "area_type IN ('gym', 'pool')", name="check_area_type_stats"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "real_time_flows",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("zip_code", sa.String(length=3), nullable=False),
        sa.Column("area_type", sa.String(length=5), nullable=False),
        sa.Column("current_count", sa.Integer(), nullable=False),
        sa.Column(
            "timestamp",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.CheckConstraint("area_type IN ('gym', 'pool')", name="check_area_type_flow"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_real_time_flows_zip_timestamp",
        "real_time_flows",
        ["zip_code", "timestamp"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_real_time_flows_zip_timestamp", table_name="real_time_flows")
    op.drop_table("real_time_flows")
    op.drop_table("historical_stats")
    # ### end Alembic commands ###
