"""修改歷史統計記錄表欄位

Revision ID: 415a08a61212
Revises: fd00725a3a98
Create Date: 2025-07-31 00:43:42.239096

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "415a08a61212"
down_revision: Union[str, Sequence[str], None] = "fd00725a3a98"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "historical_stats", sa.Column("total_count", sa.Integer(), nullable=False)
    )
    op.drop_column("historical_stats", "avg_count")
    op.drop_column("historical_stats", "max_count")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "historical_stats",
        sa.Column("max_count", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "historical_stats",
        sa.Column(
            "avg_count",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("historical_stats", "total_count")
    # ### end Alembic commands ###
