"""歷史統計增加統計指標

Revision ID: 7705dde34b40
Revises: 415a08a61212
Create Date: 2025-07-31 01:01:58.144805

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7705dde34b40"
down_revision: Union[str, Sequence[str], None] = "415a08a61212"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "historical_stats",
        sa.Column("stats_type", sa.String(length=10), nullable=False),
    )
    op.add_column(
        "historical_stats", sa.Column("avg_count", sa.Float(), nullable=False)
    )
    op.add_column(
        "historical_stats", sa.Column("max_count", sa.Integer(), nullable=False)
    )
    op.add_column(
        "historical_stats", sa.Column("min_count", sa.Integer(), nullable=False)
    )
    op.add_column(
        "historical_stats", sa.Column("start_date", sa.Date(), nullable=False)
    )
    op.add_column("historical_stats", sa.Column("end_date", sa.Date(), nullable=False))
    op.create_unique_constraint(
        "unique_stats_constraint",
        "historical_stats",
        ["zip_code", "area_type", "stats_type", "start_date"],
    )
    op.drop_column("historical_stats", "date")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "historical_stats",
        sa.Column("date", sa.DATE(), autoincrement=False, nullable=False),
    )
    op.drop_constraint("unique_stats_constraint", "historical_stats", type_="unique")
    op.drop_column("historical_stats", "end_date")
    op.drop_column("historical_stats", "start_date")
    op.drop_column("historical_stats", "min_count")
    op.drop_column("historical_stats", "max_count")
    op.drop_column("historical_stats", "avg_count")
    op.drop_column("historical_stats", "stats_type")
    # ### end Alembic commands ###
