"""修改約束條件

Revision ID: 93f75bc163e9
Revises: 7705dde34b40
Create Date: 2025-07-31 14:08:53.410879

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "93f75bc163e9"
down_revision: Union[str, Sequence[str], None] = "7705dde34b40"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
