"""移除總人數統計

Revision ID: cc6049865670
Revises: 964c04c2068c
Create Date: 2025-07-31 14:46:42.234433

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cc6049865670"
down_revision: Union[str, Sequence[str], None] = "964c04c2068c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("historical_stats", "total_count")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "historical_stats",
        sa.Column("total_count", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
